routes/web.php
<?php
/**
*|--------------------------------------------------------------------------
*| Web Routes
*|--------------------------------------------------------------------------
*|
*| Here is where you can register web routes for your application. These
*| routes are loaded by the RouteServiceProvider within a group which
*| contains the "web" middleware group. Now create something great!
*|.
*/

// header('Access-Control-Allow-Origin:  *');

Auth::routes();

Route::name('dashboard.')->group(function () {
    Route::group(['middleware' => ['auth']], function () {
        // Admin Dashboard Index page
        Route::get('/', 'DashboardController@index')->name('index');

        // TODO: Change to Users Controller
        // Admin Dashboard Users Table
        Route::get('/users', 'DashboardController@users')->name('users');


        // TODO: Change to Sites Controller
        // Admin Dashboard Sites Table
        Route::get('/sites', 'DashboardController@sites')->name('sites.index');

        // Show Site Edit form
        Route::get('/sites/{site}/edit', 'Admin\SiteController@edit')->name('sites.edit');

        // Show create Site form
        Route::get('/site/new', 'Admin\SiteController@create')->name('sites.create');

        // POST Site edits
        Route::put('/sites/{site}', 'Admin\SiteController@update')->name('sites.update');

        // POST Site create
        Route::post('/sites', 'Admin\SiteController@store')->name('sites.store');

        // POST delete SITE
        Route::delete('/sites/{site}', 'Admin\SiteController@destroy')->name('sites.destroy');

        Route::name('profile.')->group(function () {
            Route::get('/profile', 'ProfileController@index')->name('index');
        });

        Route::get('/oauth', function () {
            return view('admin.oauth.index');
        })->name('oauth');
    });
});

app/Site.php
<?php
/**
 * Site Model.
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Site Model class.
 */
class Site extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'url', 'picture', 'added_by',
    ];

    /**
     * The attributes are not assignable.
     *
     * @var array
     */
    protected $attributes = [
        'click_amt' => 0,
    ];

    /**
     * A site belongs to one \App\Category.
     *
     * @return Model
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function users()
    {
        return $this->belongsToMany('App\User', 'favorites');
    }
}

app/Http/Controllers/Admin/SiteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Site;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.sites.index', [
            'sites' => Site::all(),
            'user' => Auth::user(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.sites.create', ['user' => Auth::user()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'title' => 'required',
            'category' => 'required',
            'url' => 'required|url',
            'screenshot' => 'image|required',
        ]);
        $site = new Site();

        $site->title = $request->title;

        $site->category()->associate($request->category);

        $site->url = $request->url;

        $screenshotPath = $request->screenshot->store('sites');

        $site->screenshot = $screenshotPath;

        $site->save();

        return back()->with('status', 'Site Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Site $site
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Site $site)
    {
        return $site;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Site $site
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.sites.edit', [
            'site' => Site::findOrFail($id),
            'user' => Auth::user(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Site                $site
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Site $site)
    {
        $validate = $request->validate([
            'title' => 'required',
            'category' => 'digits:1',
            'url' => 'url',
            'screenshot' => 'mimes:jpeg,bmp,png',
        ]);

        $site->title = $request->title;

        $site->category()->associate($request->category);

        $site->url = $request->url;

        if ($request->hasFile('screenshot')) {
            $path = $request->screenshot->store('sites');
            $site->screenshot = $path;
        }

        if ($site->isClean()) {
            // Site UNCHANGED
            return back();
        } else {
            // Site CHANGED
            $site->save();

            return back()->with('status', 'Site Updated Successfully');
        }
    }

    public function incrementClick(Request $request, Site $site)
    {
        $site->increment('click_amt');
        $site->save();

        return $site;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Site $site
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Site $site)
    {
        $site->delete();

        return back()->with('status', 'Site Deleted');
    }
}

app/Http/Controllers/Api/SiteController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Site;
use Illuminate\Http\Request;

class SiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Site::with('category')->get()->jsonSerialize();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'title' => 'required',
            'category' => 'required',
            'url' => 'required|url',
            'screenshot' => 'image|required',
        ]);

        $site = new Site();

        $site->title = $request->title;

        $site->category = $request->category;

        $site->url = $request->url;

        $screenshotPath = $request->screenshot->store('sites');

        $site->screenshot = $screenshotPath;

        $site->save();

        return $site->jsonSerialize();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Site $site
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Site $site)
    {
        return $site;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Site $site
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Site                $site
     *
     * @return \Illuminate\Http\Response
     *
    public function update(Request $request, Site $site)
    {
        $validate = $request->validate([
            'title' => 'string',
            'category' => 'digits:1',
            'url' => 'url',
            'screenshot' => 'image',
        ]);

        $site->title = $request->title;

        $site->category = $request->category;

        $site->url = $request->url;

        if ($request->hasFile('screenshot')) {
            $path = $request->screenshot->store('sites');
            $site->screenshot = $path;
        }
        $site->save();

        return 'Success!!';
    }
     */
    public function incrementClick(Request $request, Site $site)
    {
        $site->increment('click_amt');
        $site->save();

        return $site;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Site $site
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Site $site)
    {
    }
}

resources/views/admin/sites/create.blade.php
@extends('layouts.admin')
@section('content')

@if (session('status'))
<div id="statusMsg" class="alert alert-success status-msg">{{ session('status') }}</div>
@endif

<div class="row">
    <div class="col">
        <h1>Create Site</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form id="siteCreateFrm" method="POST" action="{{ route('dashboard.sites.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group row">
                <label for="inputTitle" class="col-sm-1 col-form-label">Title</label>
                <div class="col-sm-10">
                    <input id="inputTitle" name="title" type="text" placeholder="Enter Title" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputCategory" class="col-sm-1 col-form-label">Category</label>
                <div class="col-sm-10">
                    <select id="inputCategory" name="category" class="form-control">
                    <option value="1">Personal</option>
                    <option value="2">Comics</option>
                    <option value="3">Entertainment</option>
                    <option value="4">Shopping</option>
                    <option value="5">Bills</option>
                    <option value="6">Banking</option>
                    <option value="7">EVE</option>
                    <option value="8">Elite Dangerous</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="inputUrl" class="col-sm-1 col-form-label">URL</label>
                <div class="col-sm-10">
                    <input id="inputUrl" type="text" name="url" placeholder="http://www.example.com" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Screenshot</label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input id="fileInput" type="file" name="screenshot" class="custom-file-input">
                        <label for="screenshotFile" class="custom-file-label" id="fileInputLabel">Pick Screenshot</label>
                    </div>
                </div>
            </div>
            <button class="btn btn-danger" type="button" id="siteCreateCancelBtn">Cancel</button>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/sites/edit.blade.php
@extends('layouts.admin')
@section('content')

@if (session('status'))
<div id="statusMsg" class="alert alert-success status-msg">{{ session('status') }}</div>
@endif

<h1>Edit Site</h1>
<form id="editForm" method="POST" enctype="multipart/form-data" action="{{ route('dashboard.sites.update', [ 'site' => $site->id ]) }}">
    @method('PUT') @csrf
    <div class="form-group row">
        <label for="title" class="col-sm-1 col-form-label">Title</label>
        <div class="col-sm-10">
            <input id="title" name="title" type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title', $site->title) }}">
            @foreach ($errors->get('title') as $message)
                <div class="invalid-feedback">{{ $message }} </div>
            @endforeach
        </div>

    </div>
    <div class="form-group row">
        <label for="category" class="col-sm-1 col-form-label">Category</label>
        <div class="col-sm-10">
            <select id="category" name="category" class="form-control {{ $errors->has('category') ? 'is-invalid' : '' }}">
                @if ($site->category === 1)
                    <option value="1" selected>Personal</option>
                @else
                    <option value="1">Personal</option>
                @endif
                @if ($site->category === 2)
                    <option value="2" selected>Comics</option>
                @else
                    <option value="2">Comics</option>
                @endif
                @if ($site->category === 3)
                    <option value="3" selected>Entertainment</option>
                @else
                    <option value="3">Entertainment</option>
                @endif
                @if ($site->category === 4)
                    <option value="4" selected>Shopping</option>
                @else
                    <option value="4">Shopping</option>
                @endif
                @if ($site->category === 5)
                    <option value="5" selected>Bills</option>
                @else
                    <option value="5">Bills</option>
                @endif
                @if ($site->category === 6)
                    <option value="6" selected>Banking</option>
                @else
                <option value="6">Banking</option>
                @endif
                @if ($site->category === 7)
                    <option value="7" selected>EVE</option>
                @else
                    <option value="7">EVE</option>
                @endif
                @if ($site->category === 8)
                    <option value="8" selected>Elite Dangerous</option>
                @else
                    <option value="8">Elite Dangerous</option>
                @endif
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label for="url" class="col-sm-1 col-form-label">URL</label>
        <div class="col-sm-10">
            <input id="url" name="url" type="text" class="form-control {{ $errors->has('url') ? 'is-invalid' : '' }}" value="{{ old('url', $site->url) }}">
            @foreach ($errors->get('url') as $message)
                <div class="invalid-feedback">{{ $message }} </div>
            @endforeach
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label">Screenshot</label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input id="screenshot" class="custom-file-input {{ $errors->has('screenshot') ? 'is-invalid' : '' }}" name="screenshot" type="file"
                    value="{{ old('screenshot', $site->screenshot) }}" accept="image/*">
                <label for="screenshot" class="custom-file-label">{{ old('screenshot', $site->screenshot) }}</label>
                @foreach ($errors->get('screenshot') as $message)
                <div class="invalid-feedback">{{ $message }} </div>
                @endforeach
            </div>
        </div>
    </div>
    <button class="btn btn-primary" type="button">Cancel</button>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
@endsection

resources/views/admin/sites/index.blade.php
@extends('layouts.admin') 
@section('content')

@if (session('status'))
<div id="statusMsg" class="alert alert-success status-msg">{{ session('status') }}</div>
@endif

<div class="row">
    <div class="col">
        <h1>Sites</h1>
    </div>
</div>
<div class="row">
    <div class="table-responsive col-11 col-sm-12">
        <table class="table table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Category</th>
                    <th scope="col">Image</th>
                    <th scope="col">Visits</th>
                    <th scope="col">Actions</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($sites as $site)
                <tr>
                    <td scope="row" class="align-middle">{{ $site->title }}</td>
                    <td class="align-middle">{{ $site->category->name }}</td>
                    <td class="align-middle">{{ $site->screenshot }}</td>
                    <td class="align-middle">{{ $site->click_amt }}</td>
                    <td class="align-middle">
                        <a href="{{ route('dashboard.sites.edit', ['site' => $site->id] ) }}" class="btn btn-primary btn-block">Edit</a>
                    </td>
                    <td class="align-middle">
                        <form method="POST" action="{{ route('dashboard.sites.destroy', [ 'site'=> $site->id ]) }}">
                            @csrf
                            @method('delete')
                            
                            <button class="btn btn-danger btn-block" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection