routes/web.php
<?php
/**
*|--------------------------------------------------------------------------
*| Web Routes
*|--------------------------------------------------------------------------
*|
*| Here is where you can register web routes for your application. These
*| routes are loaded by the RouteServiceProvider within a group which
*| contains the "web" middleware group. Now create something great!
*|.
*/

// header('Access-Control-Allow-Origin:  *');

Auth::routes();

Route::name('dashboard.')->group(function () {
    Route::group(['middleware' => ['auth']], function () {
        // Admin Dashboard Index page
        Route::get('/', 'DashboardController@index')->name('index');

        // TODO: Change to Users Controller
        // Admin Dashboard Users Table
        Route::get('/users', 'DashboardController@users')->name('users');


        // TODO: Change to Sites Controller
        // Admin Dashboard Sites Table
        Route::get('/sites', 'DashboardController@sites')->name('sites.index');

        // Show Site Edit form
        Route::get('/sites/{site}/edit', 'Admin\SiteController@edit')->name('sites.edit');

        // Show create Site form
        Route::get('/site/new', 'Admin\SiteController@create')->name('sites.create');

        // POST Site edits
        Route::put('/sites/{site}', 'Admin\SiteController@update')->name('sites.update');

        // POST Site create
        Route::post('/sites', 'Admin\SiteController@store')->name('sites.store');

        // POST delete SITE
        Route::delete('/sites/{site}', 'Admin\SiteController@destroy')->name('sites.destroy');

        Route::name('profile.')->group(function () {
            Route::get('/profile', 'ProfileController@index')->name('index');
        });

        Route::get('/oauth', function () {
            return view('admin.oauth.index');
        })->name('oauth');
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta id="csrf-token" name="csrf-token" value="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <header>
            @include('layouts.nav')
        </header>

        <div class="container-fluid">
            <div class="row">
                @auth
                    @if (!Route::currentRouteNamed('dashboard.profile.*'))
                        @include('layouts.sidenav')
                    @endif
                        <main role="main" class="col-sm-12 ml-sm-auto col-md-10 pt-3">
                @endauth
                @guest
                    <main role="main" class="col-md-12 pt-3">
                @endguest
                @yield('content')
                </main>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ asset('js/admin.js') }}"></script>
</body>

</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ route('dashboard.index') }}">{{ config('app.name') }}</a>

    <div id="navbar" class="navbar-collapse collapse">
        @auth
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ (!Route::currentRouteNamed('dashboard.profile.*')) ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('dashboard.index') }}">Dashboard</a>
            </li>
            <li class="nav-item {{ (Route::currentRouteNamed('dashboard.profile.*')) ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('dashboard.profile.index') }}">Profile</a>
            </li>
        </ul>
        @endauth @guest
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
        </ul>
        @else
        <div class="dropdown">
            <button id="userDropdownBtn" class="btn btn-dark dropdown-toggle" type="button" data-toggle="dropdown">{{ Auth::user()->name }}</button>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('dashboard.sites.create') }}" class="dropdown-item">Add New Site</a>
                <a class="dropdown-item text-danger" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>
            </div>
        </div>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
        @endguest
    </div>
</nav>

resources/views/layouts/sidenav.blade.php
<nav class="col-sm-3 col-md-2 d-none d-md-block sidebar border-primary">
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link {{ (Route::currentRouteNamed('dashboard.index')) ? 'active' : '' }}" href="{{ route('dashboard.index') }}">
                Overview
            </a>
        </li>
    </ul>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        Sites
    </h6>
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link {{ (Route::currentRouteNamed('dashboard.sites.index')) ? 'active' : '' }}" href="{{ route('dashboard.sites.index') }}">
                View Sites
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{ (Route::currentRouteNamed('dashboard.sites.create')) ? 'active' : '' }}" href="{{ route('dashboard.sites.create') }}">
                Add New Site
            </a>
        </li>
    </ul>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        Users
    </h6>
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link {{ (Route::currentRouteNamed('dashboard.users')) ? 'active' : '' }}" href="{{ route('dashboard.users') }}">
                View Users
            </a>
        </li>
    </ul>
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a href="{{ route('dashboard.oauth') }}" class="nav-link {{ (Route::currentRouteNamed('dashboard.oauth')) ? 'active' : '' }}">OAuth</a>
        </li>
    </ul>
</nav>